[profile.default]
solc = "0.8.32"
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = true
auto_detect_solc = true
names = true
sizes = true
via_ir = true
optimizer = true
optimizer_runs = 200
ignored_error_codes = [2424, 8429]
bytecode_hash = "none"
fs_permissions = [
    { access = "read-write", path = "./" }
]
remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@solady/=lib/solady/src/',
  '@seadrop/=lib/seadrop/src/',
  '@solmate/=lib/solmate/src/',
  '@forge-std/=lib/forge-std/src/',
  '@forge-console/=lib/forge-std/src/console.sol',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
]

[lint]
exclude_lints = [
    "unsafe-typecast",
    "mixed-case-function",
    "mixed-case-variable",
    "unwrapped-modifier-logic",
    "unused-import",
    "named-struct-fields",
    "screaming-snake-case-const",
    "unaliased-plain-import",
    "incorrect-shift",
    "unsafe-cheatcode",
    "pascal-case-struct"
]

[fmt]
line_length = 175
bracket_spacing = true
sort_imports = true
ignore = [
    "script/AddAssetsBatch.s.sol",
]

[rpc_endpoints]
localhost = "${LOCAL_RPC_URL}"
dashboard = "${FOUNDRY_DASHBOARD_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"