[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = true
chain_id = 1
auto_detect_solc = false
solc_version = "0.8.30"
evm_version = "cancun"
bytecode_hash = "ipfs"
optimizer = true
optimizer_runs = 1
libraries = []

remappings = [
]

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/YOUR_MAINNET_KEY"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/YOUR_SEPOLIA_KEY"
goerli  = "https://eth-goerli.g.alchemy.com/v2/YOUR_GOERLI_KEY"

[lint]
exclude_lints = [
    "unsafe-typecast",
    "mixed-case-function",
    "mixed-case-variable"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
